/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.contacteditor;

/**
 *
 * @author isaachm
 */
public class Calculator extends javax.swing.JFrame {
    
    int firstValue = 0;
    
    // 1 for sum, 2 for substract, 3 for division and 4 for multiply
    int operand = 0;
    

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resultTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        calcButton7 = new javax.swing.JButton();
        calcButton8 = new javax.swing.JButton();
        calcButton9 = new javax.swing.JButton();
        calcButton4 = new javax.swing.JButton();
        calcButton5 = new javax.swing.JButton();
        calcButton6 = new javax.swing.JButton();
        calcButton1 = new javax.swing.JButton();
        calcButton2 = new javax.swing.JButton();
        calcButton3 = new javax.swing.JButton();
        calcButton0 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        subsButton = new javax.swing.JButton();
        resultButton = new javax.swing.JButton();
        multButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setText("Simple Calculator");

        resultTextField.setEditable(false);
        resultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTextFieldActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        calcButton7.setBackground(new java.awt.Color(153, 255, 153));
        calcButton7.setText("7");
        calcButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton7ActionPerformed(evt);
            }
        });

        calcButton8.setBackground(new java.awt.Color(153, 255, 153));
        calcButton8.setText("8");
        calcButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton8ActionPerformed(evt);
            }
        });

        calcButton9.setBackground(new java.awt.Color(153, 255, 153));
        calcButton9.setText("9");
        calcButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton9ActionPerformed(evt);
            }
        });

        calcButton4.setBackground(new java.awt.Color(153, 255, 153));
        calcButton4.setText("4");
        calcButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton4ActionPerformed(evt);
            }
        });

        calcButton5.setBackground(new java.awt.Color(153, 255, 153));
        calcButton5.setText("5");
        calcButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton5ActionPerformed(evt);
            }
        });

        calcButton6.setBackground(new java.awt.Color(153, 255, 153));
        calcButton6.setText("6");
        calcButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton6ActionPerformed(evt);
            }
        });

        calcButton1.setBackground(new java.awt.Color(153, 255, 153));
        calcButton1.setText("1");
        calcButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton1ActionPerformed(evt);
            }
        });

        calcButton2.setBackground(new java.awt.Color(153, 255, 153));
        calcButton2.setText("2");
        calcButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton2ActionPerformed(evt);
            }
        });

        calcButton3.setBackground(new java.awt.Color(153, 255, 153));
        calcButton3.setText("3");
        calcButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton3ActionPerformed(evt);
            }
        });

        calcButton0.setBackground(new java.awt.Color(153, 255, 153));
        calcButton0.setText("0");
        calcButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButton0ActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 102, 102));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(255, 102, 102));
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        subsButton.setBackground(new java.awt.Color(255, 102, 102));
        subsButton.setText("-");
        subsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsButtonActionPerformed(evt);
            }
        });

        resultButton.setBackground(new java.awt.Color(0, 204, 204));
        resultButton.setText("=");
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });

        multButton.setBackground(new java.awt.Color(255, 102, 102));
        multButton.setText("*");
        multButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multButtonActionPerformed(evt);
            }
        });

        divButton.setBackground(new java.awt.Color(255, 102, 102));
        divButton.setText("/");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calcButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calcButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calcButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(calcButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calcButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(387, 387, 387)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(divButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcButton7)
                            .addComponent(calcButton8)
                            .addComponent(calcButton9)
                            .addComponent(clearButton))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcButton4)
                            .addComponent(calcButton5)
                            .addComponent(calcButton6)
                            .addComponent(addButton))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcButton1)
                            .addComponent(calcButton2)
                            .addComponent(calcButton3)
                            .addComponent(subsButton))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcButton0)
                            .addComponent(divButton))
                        .addGap(34, 34, 34)
                        .addComponent(multButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultButton)
                        .addGap(72, 72, 72)))
                .addComponent(exitButton)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTextFieldActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:

        System.out.print("Example");
        
        System.exit(0);
        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void calcButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton4ActionPerformed
        // TODO add your handling code here:
        
       resultTextField.setText( resultTextField.getText() + "4" );
        
    }//GEN-LAST:event_calcButton4ActionPerformed

    private void calcButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton5ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "5" );
        
    }//GEN-LAST:event_calcButton5ActionPerformed

    private void calcButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton0ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "0" );
        
    }//GEN-LAST:event_calcButton0ActionPerformed

    private void calcButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton1ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "1" );
        
    }//GEN-LAST:event_calcButton1ActionPerformed

    private void calcButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton2ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "2" );
        
    }//GEN-LAST:event_calcButton2ActionPerformed

    private void calcButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton3ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "3" );
        
    }//GEN-LAST:event_calcButton3ActionPerformed

    private void calcButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton6ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "6" );
        
    }//GEN-LAST:event_calcButton6ActionPerformed

    private void calcButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton7ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "7" );
        
    }//GEN-LAST:event_calcButton7ActionPerformed

    private void calcButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton8ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "8" );
        
    }//GEN-LAST:event_calcButton8ActionPerformed

    private void calcButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButton9ActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText( resultTextField.getText() + "9" );
        
    }//GEN-LAST:event_calcButton9ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        
        resultTextField.setText("");
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void multButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            
            firstValue = Integer.parseInt(resultTextField.getText());
            operand = 4;
            
        }
        catch(Exception e){
            
            firstValue = 0;
        }
        
        resultTextField.setText("");
        
    }//GEN-LAST:event_multButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            
            firstValue = Integer.parseInt(resultTextField.getText());
            operand = 3;
            
        }
        catch(Exception e){
            
            firstValue = 0;
        }
        
        resultTextField.setText("");
        
    }//GEN-LAST:event_divButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            
            firstValue = Integer.parseInt(resultTextField.getText());
            operand = 1;
            
        }
        catch(Exception e){
            
            firstValue = 0;
        }
        
        resultTextField.setText("");
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void subsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            
            firstValue = Integer.parseInt(resultTextField.getText());
            operand = 2;
            
        }
        catch(Exception e){
            
            firstValue = 0;
        }
        
        resultTextField.setText("");
        
    }//GEN-LAST:event_subsButtonActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        // TODO add your handling code here:
        
        switch(operand){
        
            case(1):
                
                try{
                    
                    firstValue += Integer.parseInt( resultTextField.getText() );
                    resultTextField.setText( String.valueOf(firstValue) );
                
                }
                catch(Exception e){
                    resultTextField.setText( "0" );
                }
                
                operand = 0;
                break;
                
            case(2):
                
                try{
                    
                    firstValue -= Integer.parseInt( resultTextField.getText() );
                    resultTextField.setText( String.valueOf(firstValue) );
                
                }
                catch(Exception e){
                    resultTextField.setText( "0" );
                }
                
                operand = 0;
                break;
            case(3):
                
                
                try{
                    
                    int div = Integer.parseInt( resultTextField.getText() );
                    
                    if(div != 0){
                        
                        firstValue = firstValue / Integer.parseInt( resultTextField.getText() );
                        resultTextField.setText( String.valueOf(firstValue) );
                        
                    }
                    else{
                        resultTextField.setText( "0" );
                    }
                    
                    operand = 0;
                    
                }
                catch(Exception e){
                    
                }
                
                break;
            case(4):
                
                try{
                    
                    firstValue = firstValue * Integer.parseInt( resultTextField.getText() );
                    resultTextField.setText( String.valueOf(firstValue) );
                
                }
                catch(Exception e){
                    resultTextField.setText( "0" );
                }
                
                operand = 0;
                break;
                
            default:
                firstValue = Integer.parseInt( resultTextField.getText() );
                resultTextField.setText( String.valueOf(firstValue));
            
        }
        
    }//GEN-LAST:event_resultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton calcButton0;
    private javax.swing.JButton calcButton1;
    private javax.swing.JButton calcButton2;
    private javax.swing.JButton calcButton3;
    private javax.swing.JButton calcButton4;
    private javax.swing.JButton calcButton5;
    private javax.swing.JButton calcButton6;
    private javax.swing.JButton calcButton7;
    private javax.swing.JButton calcButton8;
    private javax.swing.JButton calcButton9;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton divButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multButton;
    private javax.swing.JButton resultButton;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JButton subsButton;
    // End of variables declaration//GEN-END:variables
}
